import { MenuItem } from "@/types";

export const menuItems: MenuItem[] = [
  // Indian Cuisine
  {
    id: "ind-1",
    name: "Butter Chicken",
    description: "Tender chicken in rich tomato-based curry with butter and cream",
    price: 16.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.9,
  },
  {
    id: "ind-2",
    name: "Paneer Tikka Masala",
    description: "Grilled cottage cheese in spiced tomato gravy",
    price: 14.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "ind-3",
    name: "Chicken Biryani",
    description: "Aromatic basmati rice with spiced chicken and herbs",
    price: 17.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ind-4",
    name: "Samosa",
    description: "Crispy pastry filled with spiced potatoes and peas",
    price: 5.99,
    category: "appetizer",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.6,
  },
  {
    id: "ind-5",
    name: "Gulab Jamun",
    description: "Sweet milk dumplings soaked in rose-flavored syrup",
    price: 6.99,
    category: "dessert",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1589301773859-bb024d3f2f04?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ind-6",
    name: "Mango Lassi",
    description: "Refreshing yogurt drink with sweet mango pulp",
    price: 4.99,
    category: "beverage",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1624970081013-9c53fdd27f64?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },

  // Chinese Cuisine
  {
    id: "chi-1",
    name: "Kung Pao Chicken",
    description: "Stir-fried chicken with peanuts, vegetables, and chili peppers",
    price: 15.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "chi-2",
    name: "Sweet & Sour Pork",
    description: "Crispy pork in tangy sweet and sour sauce with bell peppers",
    price: 16.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },
  {
    id: "chi-3",
    name: "Vegetable Spring Rolls",
    description: "Crispy rolls filled with mixed vegetables",
    price: 7.99,
    category: "appetizer",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1619895092538-128341789043?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.5,
  },
  {
    id: "chi-4",
    name: "Fried Rice",
    description: "Wok-fried rice with eggs, vegetables, and soy sauce",
    price: 12.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.4,
  },
  {
    id: "chi-5",
    name: "Peking Duck",
    description: "Crispy duck with pancakes, cucumber, and hoisin sauce",
    price: 28.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1598514982901-ae62764ae75e?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },
  {
    id: "chi-6",
    name: "Jasmine Tea",
    description: "Fragrant green tea with jasmine flowers",
    price: 3.99,
    category: "beverage",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.5,
  },

  // South Indian Cuisine
  {
    id: "sid-1",
    name: "Masala Dosa",
    description: "Crispy rice crepe with spiced potato filling and sambar",
    price: 11.99,
    category: "main-course",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.8,
  },
  {
    id: "sid-2",
    name: "Idli Sambar",
    description: "Steamed rice cakes with lentil stew and coconut chutney",
    price: 9.99,
    category: "main-course",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.6,
  },
  {
    id: "sid-3",
    name: "Medu Vada",
    description: "Crispy lentil donuts served with chutney",
    price: 7.99,
    category: "appetizer",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.5,
  },
  {
    id: "sid-4",
    name: "Hyderabadi Biryani",
    description: "Fragrant rice with marinated meat and aromatic spices",
    price: 18.99,
    category: "main-course",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.9,
  },
  {
    id: "sid-5",
    name: "Payasam",
    description: "Traditional rice pudding with cardamom and nuts",
    price: 6.99,
    category: "dessert",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.6,
  },
  {
    id: "sid-6",
    name: "Filter Coffee",
    description: "Strong South Indian coffee with frothy milk",
    price: 3.99,
    category: "beverage",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },

  // Italian Cuisine
  {
    id: "ita-1",
    name: "Margherita Pizza",
    description: "Fresh mozzarella, tomatoes, and basil on thin crust",
    price: 16.99,
    category: "main-course",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ita-2",
    name: "Fettuccine Alfredo",
    description: "Creamy pasta with parmesan cheese and butter",
    price: 17.99,
    category: "main-course",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
  {
    id: "ita-3",
    name: "Bruschetta",
    description: "Toasted bread topped with fresh tomatoes, basil, and garlic",
    price: 8.99,
    category: "appetizer",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.5,
  },
  {
    id: "ita-4",
    name: "Lasagna",
    description: "Layers of pasta with meat sauce, ricotta, and mozzarella",
    price: 19.99,
    category: "main-course",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ita-5",
    name: "Tiramisu",
    description: "Classic Italian coffee-flavored dessert",
    price: 7.99,
    category: "dessert",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ita-6",
    name: "Espresso",
    description: "Strong Italian coffee shot",
    price: 3.49,
    category: "beverage",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },

  // Mexican Cuisine
  {
    id: "mex-1",
    name: "Chicken Tacos",
    description: "Soft tortillas with grilled chicken, salsa, and guacamole",
    price: 13.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "mex-2",
    name: "Beef Burrito",
    description: "Large flour tortilla with seasoned beef, rice, and beans",
    price: 15.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.6,
  },
  {
    id: "mex-3",
    name: "Nachos Supreme",
    description: "Tortilla chips with cheese, jalapeños, sour cream, and salsa",
    price: 10.99,
    category: "appetizer",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.5,
  },
  {
    id: "mex-4",
    name: "Quesadilla",
    description: "Grilled tortilla with melted cheese and vegetables",
    price: 11.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.4,
  },
  {
    id: "mex-5",
    name: "Churros",
    description: "Fried dough pastry with cinnamon sugar and chocolate sauce",
    price: 6.99,
    category: "dessert",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
  {
    id: "mex-6",
    name: "Horchata",
    description: "Sweet rice milk drink with cinnamon",
    price: 4.49,
    category: "beverage",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1622484211346-f3fc4bc87a3a?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.5,
  },

  // American Cuisine
  {
    id: "ame-1",
    name: "Classic Burger",
    description: "Angus beef patty with cheese, lettuce, tomato, and fries",
    price: 15.99,
    category: "main-course",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },
  {
    id: "ame-2",
    name: "BBQ Ribs",
    description: "Tender pork ribs with smoky BBQ sauce",
    price: 22.99,
    category: "main-course",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ame-3",
    name: "Buffalo Wings",
    description: "Crispy chicken wings tossed in spicy buffalo sauce",
    price: 12.99,
    category: "appetizer",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "ame-4",
    name: "Grilled Salmon",
    description: "Atlantic salmon with lemon butter sauce and vegetables",
    price: 24.99,
    category: "main-course",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },
  {
    id: "ame-5",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center and vanilla ice cream",
    price: 8.99,
    category: "dessert",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },
  {
    id: "ame-6",
    name: "Iced Coffee",
    description: "Cold brew coffee with milk and vanilla",
    price: 4.99,
    category: "beverage",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },

  // Additional Indian Dishes
  {
    id: "ind-7",
    name: "Chicken Tikka",
    description: "Marinated grilled chicken with Indian spices",
    price: 15.99,
    category: "appetizer",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ind-8",
    name: "Dal Makhani",
    description: "Black lentils cooked with butter, cream and spices",
    price: 12.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },
  {
    id: "ind-9",
    name: "Naan Bread",
    description: "Freshly baked Indian flatbread with butter",
    price: 3.99,
    category: "appetizer",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
  {
    id: "ind-10",
    name: "Palak Paneer",
    description: "Cottage cheese in creamy spinach gravy",
    price: 13.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: false,
    rating: 4.5,
  },

  // Additional Chinese Dishes
  {
    id: "chi-7",
    name: "Peking Duck",
    description: "Crispy roasted duck with pancakes and hoisin sauce",
    price: 28.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1583431623276-7e2e87c1a3b2?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },
  {
    id: "chi-8",
    name: "Szechuan Beef",
    description: "Spicy stir-fried beef with Szechuan peppers",
    price: 17.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: false,
    rating: 4.6,
  },
  {
    id: "chi-9",
    name: "Wonton Soup",
    description: "Delicate dumplings in clear chicken broth",
    price: 8.99,
    category: "appetizer",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: false,
    rating: 4.5,
  },
  {
    id: "chi-10",
    name: "Mapo Tofu",
    description: "Silky tofu in spicy Szechuan sauce with minced pork",
    price: 14.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1546833999-b9f581a1996d?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: false,
    rating: 4.7,
  },

  // Additional South Indian Dishes
  {
    id: "si-8",
    name: "Mysore Masala Dosa",
    description: "Crispy crepe with spicy red chutney and potato filling",
    price: 11.99,
    category: "main-course",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "si-9",
    name: "Pongal",
    description: "Rice and lentil dish tempered with spices",
    price: 9.99,
    category: "main-course",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.4,
  },
  {
    id: "si-10",
    name: "Medu Vada",
    description: "Crispy lentil fritters served with chutney",
    price: 7.99,
    category: "appetizer",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.5,
  },

  // Additional Italian Dishes
  {
    id: "ita-8",
    name: "Chicken Parmesan",
    description: "Breaded chicken breast with marinara and mozzarella",
    price: 19.99,
    category: "main-course",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1632778149955-e80f8ceca2e8?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
  {
    id: "ita-9",
    name: "Pesto Pasta",
    description: "Linguine with fresh basil pesto and pine nuts",
    price: 16.99,
    category: "main-course",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1621996346565-e3dbc646d9a9?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.6,
  },
  {
    id: "ita-10",
    name: "Caprese Salad",
    description: "Fresh mozzarella, tomatoes, and basil with balsamic",
    price: 11.99,
    category: "appetizer",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1608897013039-887f21d8c804?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.5,
  },

  // Additional Mexican Dishes
  {
    id: "mex-7",
    name: "Carnitas",
    description: "Slow-cooked pulled pork with Mexican spices",
    price: 16.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: false,
    rating: 4.6,
  },
  {
    id: "mex-8",
    name: "Elote",
    description: "Mexican street corn with mayo, cheese, and chili powder",
    price: 6.99,
    category: "appetizer",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1551462147-ff29053bfc14?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: false,
    rating: 4.5,
  },
  {
    id: "mex-9",
    name: "Tamales",
    description: "Corn dough filled with chicken, wrapped in corn husks",
    price: 12.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1562059392-096320bccc7e?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: false,
    rating: 4.7,
  },

  // Additional American Dishes
  {
    id: "ame-7",
    name: "Mac & Cheese",
    description: "Creamy macaroni with three cheese blend",
    price: 10.99,
    category: "main-course",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1543339494-b4cd4f7ba686?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },
  {
    id: "ame-8",
    name: "Philly Cheesesteak",
    description: "Sliced beef with melted cheese on a hoagie roll",
    price: 14.99,
    category: "main-course",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1561070545-e40a8c6d8082?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ame-9",
    name: "Onion Rings",
    description: "Crispy battered onion rings with ranch dip",
    price: 7.99,
    category: "appetizer",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1639024471283-03518883512d?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.4,
  },
  {
    id: "ame-10",
    name: "Apple Pie",
    description: "Classic American pie with cinnamon apples",
    price: 7.99,
    category: "dessert",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1535920527002-b35e96722eb9?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },

  // More Indian Dishes
  {
    id: "ind-11",
    name: "Tandoori Chicken",
    description: "Chicken marinated in yogurt and spices, cooked in tandoor",
    price: 17.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ind-12",
    name: "Aloo Gobi",
    description: "Potato and cauliflower curry with aromatic spices",
    price: 11.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1585937421612-70a008356fbe?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: false,
    rating: 4.4,
  },
  {
    id: "ind-13",
    name: "Chicken Korma",
    description: "Mild chicken curry with cream, yogurt and cashews",
    price: 16.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: false,
    rating: 4.6,
  },

  // More Chinese Dishes
  {
    id: "chi-11",
    name: "General Tso's Chicken",
    description: "Crispy chicken in sweet and spicy sauce",
    price: 16.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "chi-12",
    name: "Mongolian Beef",
    description: "Tender beef with scallions in savory brown sauce",
    price: 18.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: false,
    rating: 4.6,
  },
  {
    id: "chi-13",
    name: "Sesame Chicken",
    description: "Crispy chicken with honey sesame glaze",
    price: 15.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
  {
    id: "chi-14",
    name: "Hot and Sour Soup",
    description: "Spicy and tangy soup with tofu and mushrooms",
    price: 7.99,
    category: "appetizer",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: false,
    rating: 4.5,
  },

  // More South Indian Dishes
  {
    id: "si-11",
    name: "Uttapam",
    description: "Thick rice pancake with onions, tomatoes and chilies",
    price: 10.99,
    category: "main-course",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: false,
    rating: 4.5,
  },
  {
    id: "si-12",
    name: "Bisi Bele Bath",
    description: "Karnataka style spicy rice, lentils and vegetables",
    price: 11.99,
    category: "main-course",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1645177628172-a94c1f96e6db?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: false,
    rating: 4.6,
  },

  // More Italian Dishes
  {
    id: "ita-11",
    name: "Seafood Risotto",
    description: "Creamy arborio rice with mixed seafood",
    price: 24.99,
    category: "main-course",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1476124369491-c4041c8d63f5?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ita-12",
    name: "Osso Buco",
    description: "Braised veal shanks with gremolata and risotto",
    price: 29.99,
    category: "main-course",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: false,
    rating: 4.9,
  },
  {
    id: "ita-13",
    name: "Arancini",
    description: "Fried rice balls stuffed with mozzarella",
    price: 9.99,
    category: "appetizer",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1633504581786-316c8002b1b9?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.6,
  },

  // More Mexican Dishes
  {
    id: "mex-10",
    name: "Carne Asada",
    description: "Grilled marinated steak with lime and cilantro",
    price: 19.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1604908176997-125f25cc6f3d?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "mex-11",
    name: "Chiles Rellenos",
    description: "Roasted poblano peppers stuffed with cheese",
    price: 14.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1565299585323-38d6b0865b47?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: false,
    rating: 4.7,
  },
  {
    id: "mex-12",
    name: "Pozole",
    description: "Traditional Mexican soup with hominy and pork",
    price: 13.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: false,
    rating: 4.6,
  },

  // More American Dishes
  {
    id: "ame-11",
    name: "New York Strip Steak",
    description: "12oz premium strip steak with garlic butter",
    price: 32.99,
    category: "main-course",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1558030006-450675393462?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },
  {
    id: "ame-12",
    name: "Clam Chowder",
    description: "Creamy New England style clam soup",
    price: 9.99,
    category: "appetizer",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1569718212165-3a8278d5f624?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
  {
    id: "ame-13",
    name: "Cobb Salad",
    description: "Mixed greens with chicken, bacon, egg and avocado",
    price: 13.99,
    category: "appetizer",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1546793665-c74683f339c1?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: false,
    rating: 4.6,
  },
  {
    id: "ame-14",
    name: "Pancakes",
    description: "Fluffy buttermilk pancakes with maple syrup",
    price: 9.99,
    category: "dessert",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1528207776546-365bb710ee93?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
];

export const categories = [
  { id: "all", name: "All Items" },
  { id: "appetizer", name: "Appetizers" },
  { id: "main-course", name: "Main Courses" },
  { id: "dessert", name: "Desserts" },
  { id: "beverage", name: "Beverages" },
];

export const cuisineCategories = [
  { id: "all", name: "All Cuisines", icon: "🌍" },
  { id: "indian", name: "Indian", icon: "🇮🇳" },
  { id: "chinese", name: "Chinese", icon: "🇨🇳" },
  { id: "south-indian", name: "South Indian", icon: "🍛" },
  { id: "italian", name: "Italian", icon: "🇮🇹" },
  { id: "mexican", name: "Mexican", icon: "🇲🇽" },
  { id: "american", name: "American", icon: "🇺🇸" },
];
