import { MenuItem } from "@/types";

export const menuItems: MenuItem[] = [
  // Indian Cuisine
  {
    id: "ind-1",
    name: "Butter Chicken",
    description: "Tender chicken in rich tomato-based curry with butter and cream",
    price: 16.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1603894584373-5ac82b2ae398?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.9,
  },
  {
    id: "ind-2",
    name: "Paneer Tikka Masala",
    description: "Grilled cottage cheese in spiced tomato gravy",
    price: 14.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1567188040759-fb8a883dc6d8?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "ind-3",
    name: "Chicken Biryani",
    description: "Aromatic basmati rice with spiced chicken and herbs",
    price: 17.99,
    category: "main-course",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ind-4",
    name: "Samosa",
    description: "Crispy pastry filled with spiced potatoes and peas",
    price: 5.99,
    category: "appetizer",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1601050690597-df0568f70950?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.6,
  },
  {
    id: "ind-5",
    name: "Gulab Jamun",
    description: "Sweet milk dumplings soaked in rose-flavored syrup",
    price: 6.99,
    category: "dessert",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1589301773859-bb024d3f2f04?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ind-6",
    name: "Mango Lassi",
    description: "Refreshing yogurt drink with sweet mango pulp",
    price: 4.99,
    category: "beverage",
    cuisine: "indian",
    image: "https://images.unsplash.com/photo-1624970081013-9c53fdd27f64?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },

  // Chinese Cuisine
  {
    id: "chi-1",
    name: "Kung Pao Chicken",
    description: "Stir-fried chicken with peanuts, vegetables, and chili peppers",
    price: 15.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "chi-2",
    name: "Sweet & Sour Pork",
    description: "Crispy pork in tangy sweet and sour sauce with bell peppers",
    price: 16.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },
  {
    id: "chi-3",
    name: "Vegetable Spring Rolls",
    description: "Crispy rolls filled with mixed vegetables",
    price: 7.99,
    category: "appetizer",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1619895092538-128341789043?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.5,
  },
  {
    id: "chi-4",
    name: "Fried Rice",
    description: "Wok-fried rice with eggs, vegetables, and soy sauce",
    price: 12.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1603133872878-684f208fb84b?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.4,
  },
  {
    id: "chi-5",
    name: "Peking Duck",
    description: "Crispy duck with pancakes, cucumber, and hoisin sauce",
    price: 28.99,
    category: "main-course",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1598514982901-ae62764ae75e?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },
  {
    id: "chi-6",
    name: "Jasmine Tea",
    description: "Fragrant green tea with jasmine flowers",
    price: 3.99,
    category: "beverage",
    cuisine: "chinese",
    image: "https://images.unsplash.com/photo-1564890369478-c89ca6d9cde9?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.5,
  },

  // South Indian Cuisine
  {
    id: "sid-1",
    name: "Masala Dosa",
    description: "Crispy rice crepe with spiced potato filling and sambar",
    price: 11.99,
    category: "main-course",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1630383249896-424e482df921?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.8,
  },
  {
    id: "sid-2",
    name: "Idli Sambar",
    description: "Steamed rice cakes with lentil stew and coconut chutney",
    price: 9.99,
    category: "main-course",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1589301760014-d929f3979dbc?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.6,
  },
  {
    id: "sid-3",
    name: "Medu Vada",
    description: "Crispy lentil donuts served with chutney",
    price: 7.99,
    category: "appetizer",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1626074353765-517a681e40be?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.5,
  },
  {
    id: "sid-4",
    name: "Hyderabadi Biryani",
    description: "Fragrant rice with marinated meat and aromatic spices",
    price: 18.99,
    category: "main-course",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1563379091339-03b21ab4a4f8?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.9,
  },
  {
    id: "sid-5",
    name: "Payasam",
    description: "Traditional rice pudding with cardamom and nuts",
    price: 6.99,
    category: "dessert",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1563729784474-d77dbb933a9e?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.6,
  },
  {
    id: "sid-6",
    name: "Filter Coffee",
    description: "Strong South Indian coffee with frothy milk",
    price: 3.99,
    category: "beverage",
    cuisine: "south-indian",
    image: "https://images.unsplash.com/photo-1511920170033-f8396924c348?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },

  // Italian Cuisine
  {
    id: "ita-1",
    name: "Margherita Pizza",
    description: "Fresh mozzarella, tomatoes, and basil on thin crust",
    price: 16.99,
    category: "main-course",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ita-2",
    name: "Fettuccine Alfredo",
    description: "Creamy pasta with parmesan cheese and butter",
    price: 17.99,
    category: "main-course",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
  {
    id: "ita-3",
    name: "Bruschetta",
    description: "Toasted bread topped with fresh tomatoes, basil, and garlic",
    price: 8.99,
    category: "appetizer",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.5,
  },
  {
    id: "ita-4",
    name: "Lasagna",
    description: "Layers of pasta with meat sauce, ricotta, and mozzarella",
    price: 19.99,
    category: "main-course",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1574894709920-11b28e7367e3?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ita-5",
    name: "Tiramisu",
    description: "Classic Italian coffee-flavored dessert",
    price: 7.99,
    category: "dessert",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ita-6",
    name: "Espresso",
    description: "Strong Italian coffee shot",
    price: 3.49,
    category: "beverage",
    cuisine: "italian",
    image: "https://images.unsplash.com/photo-1510591509098-f4fdc6d0ff04?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },

  // Mexican Cuisine
  {
    id: "mex-1",
    name: "Chicken Tacos",
    description: "Soft tortillas with grilled chicken, salsa, and guacamole",
    price: 13.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "mex-2",
    name: "Beef Burrito",
    description: "Large flour tortilla with seasoned beef, rice, and beans",
    price: 15.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1626700051175-6818013e1d4f?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.6,
  },
  {
    id: "mex-3",
    name: "Nachos Supreme",
    description: "Tortilla chips with cheese, jalapeños, sour cream, and salsa",
    price: 10.99,
    category: "appetizer",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1513456852971-30c0b8199d4d?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.5,
  },
  {
    id: "mex-4",
    name: "Quesadilla",
    description: "Grilled tortilla with melted cheese and vegetables",
    price: 11.99,
    category: "main-course",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1618040996337-56904b7850b9?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: true,
    rating: 4.4,
  },
  {
    id: "mex-5",
    name: "Churros",
    description: "Fried dough pastry with cinnamon sugar and chocolate sauce",
    price: 6.99,
    category: "dessert",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1599599810769-bcde5a160d32?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
  {
    id: "mex-6",
    name: "Horchata",
    description: "Sweet rice milk drink with cinnamon",
    price: 4.49,
    category: "beverage",
    cuisine: "mexican",
    image: "https://images.unsplash.com/photo-1622484211346-f3fc4bc87a3a?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.5,
  },

  // American Cuisine
  {
    id: "ame-1",
    name: "Classic Burger",
    description: "Angus beef patty with cheese, lettuce, tomato, and fries",
    price: 15.99,
    category: "main-course",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },
  {
    id: "ame-2",
    name: "BBQ Ribs",
    description: "Tender pork ribs with smoky BBQ sauce",
    price: 22.99,
    category: "main-course",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1544025162-d76694265947?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "ame-3",
    name: "Buffalo Wings",
    description: "Crispy chicken wings tossed in spicy buffalo sauce",
    price: 12.99,
    category: "appetizer",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "ame-4",
    name: "Grilled Salmon",
    description: "Atlantic salmon with lemon butter sauce and vegetables",
    price: 24.99,
    category: "main-course",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },
  {
    id: "ame-5",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center and vanilla ice cream",
    price: 8.99,
    category: "dessert",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },
  {
    id: "ame-6",
    name: "Iced Coffee",
    description: "Cold brew coffee with milk and vanilla",
    price: 4.99,
    category: "beverage",
    cuisine: "american",
    image: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
];

export const categories = [
  { id: "all", name: "All Items" },
  { id: "appetizer", name: "Appetizers" },
  { id: "main-course", name: "Main Courses" },
  { id: "dessert", name: "Desserts" },
  { id: "beverage", name: "Beverages" },
];

export const cuisineCategories = [
  { id: "all", name: "All Cuisines", icon: "🌍" },
  { id: "indian", name: "Indian", icon: "🇮🇳" },
  { id: "chinese", name: "Chinese", icon: "🇨🇳" },
  { id: "south-indian", name: "South Indian", icon: "🍛" },
  { id: "italian", name: "Italian", icon: "🇮🇹" },
  { id: "mexican", name: "Mexican", icon: "🇲🇽" },
  { id: "american", name: "American", icon: "🇺🇸" },
];
