import { MenuItem } from "@/types";

export const menuItems: MenuItem[] = [
  // Appetizers
  {
    id: "app-1",
    name: "Bruschetta",
    description: "Toasted bread topped with fresh tomatoes, basil, and garlic",
    price: 8.99,
    category: "appetizer",
    image: "https://images.unsplash.com/photo-1572695157366-5e585ab2b69f?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.5,
  },
  {
    id: "app-2",
    name: "Buffalo Wings",
    description: "Crispy chicken wings tossed in spicy buffalo sauce",
    price: 12.99,
    category: "appetizer",
    image: "https://images.unsplash.com/photo-1608039755401-742074f0548d?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: true,
    popular: true,
    rating: 4.7,
  },
  {
    id: "app-3",
    name: "Mozzarella Sticks",
    description: "Golden fried mozzarella with marinara sauce",
    price: 9.99,
    category: "appetizer",
    image: "https://images.unsplash.com/photo-1531749668029-2db88e4276c7?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.3,
  },
  {
    id: "app-4",
    name: "Calamari Fritti",
    description: "Lightly breaded squid rings served with aioli",
    price: 13.99,
    category: "appetizer",
    image: "https://images.unsplash.com/photo-1599487488170-d11ec9c172f0?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },

  // Main Courses
  {
    id: "main-1",
    name: "Classic Margherita Pizza",
    description: "Fresh mozzarella, tomatoes, and basil on thin crust",
    price: 16.99,
    category: "main-course",
    image: "https://images.unsplash.com/photo-1574071318508-1cdbab80d002?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "main-2",
    name: "Grilled Salmon",
    description: "Atlantic salmon with lemon butter sauce and vegetables",
    price: 24.99,
    category: "main-course",
    image: "https://images.unsplash.com/photo-1467003909585-2f8a72700288?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },
  {
    id: "main-3",
    name: "Chicken Alfredo Pasta",
    description: "Fettuccine pasta with grilled chicken in creamy Alfredo sauce",
    price: 18.99,
    category: "main-course",
    image: "https://images.unsplash.com/photo-1645112411341-6c4fd023714a?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
  {
    id: "main-4",
    name: "Beef Burger Deluxe",
    description: "Angus beef patty with cheese, lettuce, tomato, and fries",
    price: 15.99,
    category: "main-course",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },
  {
    id: "main-5",
    name: "Vegetable Stir Fry",
    description: "Mixed vegetables with tofu in teriyaki sauce over rice",
    price: 14.99,
    category: "main-course",
    image: "https://images.unsplash.com/photo-1512058564366-18510be2db19?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: true,
    popular: false,
    rating: 4.4,
  },
  {
    id: "main-6",
    name: "Ribeye Steak",
    description: "12oz premium ribeye with garlic mashed potatoes",
    price: 32.99,
    category: "main-course",
    image: "https://images.unsplash.com/photo-1600891964092-4316c288032e?w=500&h=500&fit=crop",
    isVegetarian: false,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },

  // Desserts
  {
    id: "des-1",
    name: "Tiramisu",
    description: "Classic Italian coffee-flavored dessert",
    price: 7.99,
    category: "dessert",
    image: "https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.8,
  },
  {
    id: "des-2",
    name: "Chocolate Lava Cake",
    description: "Warm chocolate cake with molten center and vanilla ice cream",
    price: 8.99,
    category: "dessert",
    image: "https://images.unsplash.com/photo-1624353365286-3f8d62daad51?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.9,
  },
  {
    id: "des-3",
    name: "Cheesecake",
    description: "New York style cheesecake with berry compote",
    price: 7.49,
    category: "dessert",
    image: "https://images.unsplash.com/photo-1533134242443-d4fd215305ad?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.5,
  },

  // Beverages
  {
    id: "bev-1",
    name: "Fresh Lemonade",
    description: "Homemade lemonade with mint",
    price: 3.99,
    category: "beverage",
    image: "https://images.unsplash.com/photo-1523677011781-c91d1bbe2f9d?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.6,
  },
  {
    id: "bev-2",
    name: "Iced Coffee",
    description: "Cold brew coffee with milk and vanilla",
    price: 4.99,
    category: "beverage",
    image: "https://images.unsplash.com/photo-1517487881594-2787fef5ebf7?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: true,
    rating: 4.7,
  },
  {
    id: "bev-3",
    name: "Mango Smoothie",
    description: "Fresh mango blended with yogurt and honey",
    price: 5.99,
    category: "beverage",
    image: "https://images.unsplash.com/photo-1505252585461-04db1eb84625?w=500&h=500&fit=crop",
    isVegetarian: true,
    isSpicy: false,
    popular: false,
    rating: 4.5,
  },
];

export const categories = [
  { id: "all", name: "All Items" },
  { id: "appetizer", name: "Appetizers" },
  { id: "main-course", name: "Main Courses" },
  { id: "dessert", name: "Desserts" },
  { id: "beverage", name: "Beverages" },
];
